### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by gulrotkake** [JulienPalard/vt100-emulator#3]
I'd love to re-use some of this code in a project I'm working on, to avoid re-implementing much the vt100 specification :), but I can't seem to find any licensing terms. Is this library licensed under a free/open license?

Great work btw!

**Comment by JulienPalard** [comment]
You're so right ^-^ I fixed that, proof-read my old README, and added an example in Python.

Look like this project has gone unmaintained and unused for 4 years, but as it's 100% in pedantic C89,  it still work and tests still obviously pass. Also porting it to Python 3 should be seamless (just have to read the swig doc about it, probably just a parameter ? Hope). Yet I don't know if you want to use the C or the Python API, both work.

Don't hesitate to look at `run_tests.py` and `src/test.c` for usage examples, but it look like you're already a bit familiar with it.

> Great work btw!

Thanks a lot, don't hesitate if you need something, I'm living in the CET (very near the UTC) time zone so I'll may no be fast to reply to your tickets depending on your timezone ^-^ but I'll do :-)
